# Generated by Django 4.2 on 2023-06-20 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0002_order_alter_product_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart_id",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="price",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
