# Generated by Django 4.2 on 2023-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BodyMeasurements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bust", models.FloatField(max_length=10, verbose_name="Bust")),
                ("waist", models.FloatField(max_length=10, verbose_name="Waist")),
                ("hips", models.FloatField(max_length=10, verbose_name="Hips")),
                ("neck", models.FloatField(max_length=10, verbose_name="Neck")),
                ("chest", models.FloatField(max_length=10, verbose_name="Chest")),
                ("shoulder", models.FloatField(max_length=10, verbose_name="Shoulder")),
                ("sleeve", models.FloatField(max_length=10, verbose_name="Sleeve")),
                (
                    "shoulder_to_waist",
                    models.FloatField(max_length=10, verbose_name="Shoulder to waist"),
                ),
                (
                    "shoulder_to_floor",
                    models.FloatField(max_length=10, verbose_name="Shoulder to floor"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length="250",
                        verbose_name="Additional information",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
