# Generated by Django 4.2 on 2023-05-09 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="default.jpg", upload_to="profile_images"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BodyMeasurements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bust", models.FloatField(max_length=10, verbose_name="Bust")),
                ("waist", models.FloatField(max_length=10, verbose_name="Waist")),
                ("hips", models.FloatField(max_length=10, verbose_name="Hips")),
                ("neck", models.FloatField(max_length=10, verbose_name="Neck")),
                ("chest", models.FloatField(max_length=10, verbose_name="Chest")),
                ("shoulder", models.FloatField(max_length=10, verbose_name="Shoulder")),
                ("sleeve", models.FloatField(max_length=10, verbose_name="Sleeve")),
                (
                    "shoulder_to_waist",
                    models.FloatField(max_length=10, verbose_name="Shoulder to waist"),
                ),
                (
                    "shoulder_to_floor",
                    models.FloatField(max_length=10, verbose_name="Shoulder to floor"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=250,
                        verbose_name="Additional information",
                    ),
                ),
                (
                    "measure_model",
                    models.ImageField(default="body_measurements.jpg", upload_to=""),
                ),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
