# Generated by Django 4.2 on 2023-07-10 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, default="default.jpg", upload_to="profile_images"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BodyMeasurements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bust",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Bust"
                    ),
                ),
                (
                    "waist",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Waist"
                    ),
                ),
                (
                    "hips",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[validators.validate_positive],
                        verbose_name="Hips",
                    ),
                ),
                (
                    "neck",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Neck"
                    ),
                ),
                (
                    "chest",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Chest"
                    ),
                ),
                (
                    "shoulder",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Shoulder"
                    ),
                ),
                (
                    "sleeve",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Sleeve"
                    ),
                ),
                (
                    "shoulder_to_waist",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Shoulder to waist"
                    ),
                ),
                (
                    "shoulder_to_floor",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Shoulder to floor"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Additional information",
                    ),
                ),
                (
                    "measure_model",
                    models.ImageField(
                        blank=True,
                        default="body_measurements.jpg",
                        null=True,
                        upload_to="",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
