# Generated by Django 4.2 on 2023-06-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymeasurements",
            name="bust",
            field=models.FloatField(blank=True, max_length=10, verbose_name="Bust"),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="chest",
            field=models.FloatField(blank=True, max_length=10, verbose_name="Chest"),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="hips",
            field=models.FloatField(blank=True, max_length=10, verbose_name="Hips"),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="measure_model",
            field=models.ImageField(
                blank=True, default="bodymeasurements.jpg", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="neck",
            field=models.FloatField(blank=True, max_length=10, verbose_name="Neck"),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="shoulder",
            field=models.FloatField(blank=True, max_length=10, verbose_name="Shoulder"),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="shoulder_to_floor",
            field=models.FloatField(
                blank=True, max_length=10, verbose_name="Shoulder to floor"
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="shoulder_to_waist",
            field=models.FloatField(
                blank=True, max_length=10, verbose_name="Shoulder to waist"
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="sleeve",
            field=models.FloatField(blank=True, max_length=10, verbose_name="Sleeve"),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="waist",
            field=models.FloatField(blank=True, max_length=10, verbose_name="Waist"),
        ),
    ]
