# Generated by Django 4.2 on 2023-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_bodymeasurements_bust_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymeasurements",
            name="bust",
            field=models.FloatField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="measure_model",
            field=models.ImageField(
                blank=True, default="body_measurements.jpg", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="profile_images"
            ),
        ),
    ]
