# Generated by Django 4.2 on 2023-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymeasurements",
            name="comment",
            field=models.TextField(
                blank=True, max_length=250, verbose_name="Additional information"
            ),
        ),
    ]
