# Generated by Django 4.2 on 2023-05-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_bodymeasurements_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodymeasurements",
            name="avatar",
            field=models.ImageField(default="bodymeasurements.jpg", upload_to=""),
        ),
    ]
