# Generated by Django 4.2 on 2023-05-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_bodymeasurements_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bodymeasurements",
            old_name="avatar",
            new_name="measure_model",
        ),
    ]
