# Generated by Django 4.2 on 2023-06-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_bodymeasurements_bust_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymeasurements",
            name="waist",
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
