# Generated by Django 4.2 on 2023-06-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_bodymeasurements_waist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bodymeasurements",
            name="last_updated",
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="bust",
            field=models.FloatField(
                blank=True, max_length=10, null=True, verbose_name="Bust"
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="waist",
            field=models.FloatField(
                blank=True, max_length=10, null=True, verbose_name="Waist"
            ),
        ),
    ]
