# Generated by Django 4.2 on 2023-06-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_bodymeasurements_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodymeasurements",
            name="last_updated",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
