# Generated by Django 4.2 on 2023-06-19 18:07

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_bodymeasurements_bust_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymeasurements",
            name="bust",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Bust"
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="chest",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Chest"
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="hips",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[validators.validate_positive],
                verbose_name="Hips",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="neck",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Neck"
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="shoulder",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Shoulder"
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="sleeve",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Sleeve"
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="waist",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Waist"
            ),
        ),
    ]
