# Generated by Django 4.2 on 2023-06-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_bodymeasurements_bust_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymeasurements",
            name="shoulder_to_floor",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Shoulder to floor"
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="shoulder_to_waist",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Shoulder to waist"
            ),
        ),
    ]
