# Generated by Django 4.2 on 2023-07-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_contactus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactus",
            name="user",
        ),
    ]
